name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: true
          addAssignees: true
          reviewers: |
            bubkoo
            bubkoo
          assignees: |
            bubkoo
          numberOfReviewers: 1
          skipKeywords: |
            wip
          excludeLabels: |
            dependencies
            wip
